Add `profileMode` argument
hey24sheep/azure-flutter-tasks pull request #54
Opened 2022-09-29 07:56 UTC by spydon

Adding the `profileMode` argument so that it adds the `--profile` flag to `flutter build`. (defaults to false)

2022-09-30 04:23 UTC, hey24sheep commented
@spydon Hi, thank you for the PR. I have added a few notes.

2022-09-30 06:07 UTC, spydon commented
> @spydon Hi, thank you for the PR. I have added a few notes. 

Hey! I think you forgot to submit the review,, because I can't see any comments?

2022-09-30 13:25 UTC, hey24sheep requested changes

2022-09-30 13:42 UTC, spydon commented on tasks/build/index.js
> +            yield buildIpa(flutterPath, targetPlatform == "simulator", codesign, buildName, buildNumber, debugMode, profileMode, buildFlavour, entryPoint, dartDefine, dartDefineMulti, isVerbose, extr
Done! Added it to web too.

2022-09-30 14:08 UTC, hey24sheep commented
@spydon thanks for quick changes, but you made changes to .JS files, they get generated by .TS compiler. You need to edit these in .TS files also, `profileMode` has to be added to "task.json" so it can show up on UI of Azure Builds within this folder. Have a look [here](https://github.com/hey24sheep/azure-flutter-tasks/pull/50/files). you can refer to this PR for a guide.

2022-10-03 19:06 UTC, spydon commented
@hey24sheep fixed!

2022-10-04 05:27 UTC, hey24sheep approved these changes

2022-10-04 05:27 UTC, merged